name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: db migrations
      run: |
        cd server
        npm install
        NODE_ENV=testing npm run test
        npm run adonis migration:run
        
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run now -- \
          -e APP_KEY="$APP_KEY" \
          -e DATABASE_URL="$DATABASE_URL" \
          -e DB_CONNECTION=pg \
          -e GOOGLE_MAPS_KEY="$GOOGLE_MAPS_KEY" \
          --token="$NOW_TOKEN"
      env:
        CI: true
        APP_KEY: ${{ secrets.APP_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
