name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: nestjs
      run: |
        cd nestjs
        npm install
        npm run test
        npm run build

    - name: server
      run: |
        cd adonis
        npm install
        npm run adonis -- migration:run
        npm run adonis -- seed        
        npm run test
      env:
        NODE_ENV: testing
        ENV_PATH: .env.testing

    - name: migration
      run: |
        cd adonis
        npm install
        npm run adonis -- migration:run
      env:
        ENV_SILENT: true
        APP_KEY: ${{ secrets.APP_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: nextjs
      run: |
        cd client
        npm install
        npm run build --if-present

      env:
        CI: true
        APP_KEY: ${{ secrets.APP_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}

    - name: deploy
      run: |
        now \
          -e APP_KEY="$APP_KEY" \
          -e DATABASE_URL="$DATABASE_URL" \
          -e DB_CONNECTION=pg \
          -e GOOGLE_MAPS_KEY="$GOOGLE_MAPS_KEY" \
          --token="$NOW_TOKEN"

      env:
        CI: true
        APP_KEY: ${{ secrets.APP_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
