name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:

    - uses: actions/checkout@v1

    - name: Vercel Action
      uses: amondnet/vercel-action@v19.0.1+3

      env:
        CI: true
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
